import '../../../config/barrel.dart';

class AppColors {
  static const Color white = Color(0xFFFFFFFF);
  static const Color primary = Color(0xFF3952DE);
  static const Color purpleLight = Color(0xFFC27AFF);
  static const Color purple = Color(0xFFAD46FF);
  static const Color orange = Color(0xFFFF6900);
  static const Color green = Color(0xFF00C950);
  static const Color purpleOverlay = Color(0x6659168B);
  static const Color magentaOverlay = Color(0x66861043);
  static const Color gold = Color(0xFFF0B100);
  static const Color goldAccent = Color(0xFFF9A91E);
  static const Color darkSlate = Color(0xFF1E232B);
  static const Color blue = Color(0xFF167EE6);
  static const Color red = Color(0xFFFB2C36);
  static const Color lightBlue = Color(0xCCBEDBFF);
  static const Color greyDark = Color(0xFF454545);
  static const Color greyLight = Color(0xFFD5D7DA);
  static const Color black05 = Color(0x0D0A0D12);
  static const Color greyMedium = Color(0xFF717680);
  static const Color dark = Color(0xFF111111);
  static const Color darkBackground = Color(0xFF16161C);
  static const Color charcoal = Color(0xFF333333);
  static const Color blueBright = Color(0xFF3B82F6);
  static const Color blueSky = Color(0xFF60A5FA);
  static const Color mutedRoseGray = Color(0xFFB4A7A9);
  static const Color black = Color(0xFF000000);
  static const Color magenta = Color(0xFFE60076);
  static const Color slateBlue = Color(0xFF4A5A70);
  static const Color slateBlueGray = Color(0xFF536074);
  static const Color blueGrey = Color(0xFF90A4AE);
  static const Color deepBlueOverlay = Color(0x331C398E);
  static const Color deepNavy = Color(0xFF080717);
  static const Color calendarBorderBlue = Color(0xFF2B7FFF);
  static const Color blueOverlay = Color(0x0D2B7FFF);
  static const Color purpleOverLay = Color(0x0DAD46FF);
  static const Color greenOverlay = Color(0x0D00C950);
  static const Color blackOverlay = Color(0x33000000);
  static const Color darkBlack = Color(0xFF0A0A0A);
  static const Color lightBlueAccent = Color(0xFF42A5F5);
  static const Color lightPurple = Color(0xFFAB47BC);
  static const Color greenAccent = Color(0xFF66BB6A);
  static const Color lightBlueAcc = Color(0xFF64B5F6);
}
